- name: set status to ev_work_in_progress
  include_role: 
    name: itop_role
  vars:
    comment: Maj COMPTE DE SERVICE INDUS
    operation: core/apply_stimulus
    class_itop: Incident
    key: SELECT Incident WHERE id=\"{{ vNewIncidentId }}\"
    output_fields: ref
    comment: Maj COMPTE DE SERVICE INDUS
    fields: {"agent_id": "SELECT Person WHERE friendlyname=\"{{iTopContact}}\""}
    stimulus: ev_work_in_progress

- name: set vServerStatus
  set_fact:
    vServerStatus: "KO Technique, impossible de maj le ticket."
  when: interface_itop_request_response.json.code != 0

- name: maj original itop Incidet/article server
  include_role: 
    name: itop_role
  vars:
    operation: core/update
    class_itop: Incident
    key: SELECT Incident WHERE id=\"{{ vNewIncidentId }}\"
    output_fields: ref
    comment: Maj COMPTE DE SERVICE INDUS
    fields: {"public_log": "Message automatique: Fermeture du ticket car en doublon de {{ vIncidentId }}."}

- name: set vServerStatus
  set_fact:
    vServerStatus: "KO Technique, impossible de maj le ticket."
  when: interface_itop_request_response.json.code != 0

- name: set status to ev_resolve
  include_role: 
    name: itop_role
  vars:
    comment: Maj COMPTE DE SERVICE INDUS
    operation: core/apply_stimulus
    class_itop: Incident
    key: SELECT Incident WHERE id=\"{{ vNewIncidentId }}\"
    output_fields: ref
    comment: Maj COMPTE DE SERVICE INDUS
    fields: {"edf_code_cloture_id": "2","solution": "Action Ok"}
    stimulus: ev_resolve

- name: set vServerStatus
  set_fact:
    vServerStatus: "KO Technique, impossible de cloturer le ticket."
  when: interface_itop_request_response.json.code != 0

- name: maj original itop Incidet/article server
  include_role: 
    name: itop_role
  vars:
    operation: core/update
    class_itop: Incident
    key: SELECT Incident WHERE id=\"{{ vIncidentId }}\"
    output_fields: ref
    comment: Maj COMPTE DE SERVICE INDUS
    fields: {"public_log": "Message automatique: Le ticket {{ vNewIncidentId }} a été clos car en doublon de celui-ci."}

- name: set vServerStatus
  set_fact:
    vServerStatus: "KO Technique, impossible de maj le ticket."
  when: interface_itop_request_response.json.code != 0